# Generated by Django 4.0.5 on 2022-07-24 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kcal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(default='', verbose_name='키')),
                ('weight', models.PositiveIntegerField(default='', verbose_name='체중')),
                ('age', models.PositiveIntegerField(default='', verbose_name='나이')),
                ('sex', models.CharField(choices=[('male', '남자'), ('female', '여자')], max_length=200, verbose_name='성별')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kcal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
