# Generated by Django 4.0.5 on 2022-07-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcalculatorapp', '0002_kcal_actv'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcal',
            name='tension',
            field=models.CharField(choices=[('low', '저강도'), ('mid', '중강도'), ('high', '고강도')], default=1, max_length=200, verbose_name='성별'),
            preserve_default=False,
        ),
    ]
