# Generated by Django 4.0.5 on 2022-08-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcalculatorapp', '0004_kcal_goal_alter_kcal_tension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcal',
            name='goal',
            field=models.CharField(choices=[('diet', '다이어트-체지방감소'), ('lean', '린매스-근육증가')], max_length=200, verbose_name='운동목적'),
        ),
        migrations.AlterField(
            model_name='kcal',
            name='tension',
            field=models.CharField(choices=[(0.45, '저강도'), (0.55, '중강도'), (0.65, '고강도')], max_length=200, verbose_name='운동강도'),
        ),
    ]
