# Generated by Django 4.0.5 on 2022-08-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcalculatorapp', '0005_alter_kcal_goal_alter_kcal_tension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcal',
            name='tension',
            field=models.FloatField(choices=[(0.45, '저강도'), (0.55, '중강도'), (0.65, '고강도')], max_length=200, verbose_name='운동강도'),
        ),
    ]
