# Generated by Django 4.0.5 on 2022-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcalculatorapp', '0006_alter_kcal_tension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcal',
            name='weight',
            field=models.FloatField(default='', verbose_name='체중'),
        ),
    ]
