# Generated by Django 4.0.5 on 2022-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcalculatorapp', '0007_alter_kcal_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcal',
            name='speed',
            field=models.CharField(choices=[(300, '천천히'), (500, '빠르게')], default=1, max_length=200, verbose_name='증/감 속도'),
            preserve_default=False,
        ),
    ]
