# Generated by Django 4.0.5 on 2022-08-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcalculatorapp', '0008_kcal_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kcal',
            name='speed',
            field=models.CharField(choices=[(300, '천천히'), (500, '빠르게')], max_length=200, verbose_name='체중변화 속도'),
        ),
    ]
