# Generated by Django 4.0.5 on 2022-08-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
    ]
